name: CI (Lint + Tests) & Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Run deploy to dev org after CI'
        required: false
        default: 'false'  # set to 'true' when triggering manually to deploy

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run lint
        run: |
          if [ -f "eslint.config.js" ] || [ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ]; then
            npx eslint .
          else
            echo "No ESLint config, skipping."
          fi

      - name: Run tests (Jest)
        run: |
          if [ -f "jest.config.js" ] || [ -f "jest.config.cjs" ]; then
            npm test -- --ci --reporters=default --reporters=jest-junit
          else
            echo "No Jest config, skipping."
          fi

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy == 'true' }}
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm i -g @salesforce/cli

      - name: Auth to Salesforce (via SFDX_AUTH_URL secret)
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > ./auth.txt
          sf org login sfdx-url --sfdx-url-file ./auth.txt --alias ci-org --set-default
          rm -f ./auth.txt
          sf org whoami

      - name: Validate source (check-only)
        run: sf project deploy validate --tests "RunLocalTests" --wait 30 || echo "Validation skipped/flexible"

      - name: Deploy to dev org
        run: sf project deploy start --source-dir force-app --ignore-conflicts --wait 30
