name: CI (Lint + Tests) & Deploy

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy:
        description: "Run deploy to dev org after CI"
        required: false
        default: "false"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install deps
        run: npm ci --no-audit --no-fund --legacy-peer-deps

      - name: Run lint (only if LWC/Aura exist)
        run: |
          FILES=$(git ls-files '**/lwc/**/*.js' '**/aura/**/*.js' | wc -l)
          if [ "$FILES" -gt 0 ]; then
            npm run lint
          else
            echo "No LWC/Aura JS to lint — skipping."
          fi

      - name: Run tests (LWC Jest) if present
        run: |
          if [ -d "force-app/main/default/lwc" ]; then
            npm run test -- --ci --reporters=default --reporters=jest-junit
          else
            echo "No LWC folder — skipping Jest."
          fi

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy == 'true' }}
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm i -g @salesforce/cli

      - name: Auth to Salesforce (via SFDX_AUTH_URL secret)
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > ./auth.txt
          sf org login sfdx-url --sfdx-url-file ./auth.txt --alias ci-org --set-default
          rm -f ./auth.txt
          sf org display --target-org ci-org --verbose

      - name: Validate source (check-only)
        run: sf project deploy validate --tests "RunLocalTests" --wait 30 || echo "Validation skipped/flexible"

      - name: Deploy to dev org
        run: sf project deploy start --source-dir force-app --ignore-conflicts --wait 30
